name: Upload Repository to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main
      - image-upload-pipeline # remove after testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      S3_BUCKET: wicked-woods-distribution-bucket
      DISTRIBUTION_ID: E3LMXX06QSLNNW

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create zip of repository
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x "*.png" "*.jpg" "*.jpeg" "*.gif" "*.bmp" "*.tiff" "*.webp" "*.ico" "*.svg"

      - name: Upload zip to S3
        run: |
          aws s3 cp ${{ github.event.repository.name }}.zip s3://${S3_BUCKET}/${{ github.event.repository.name }}.zip

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://${S3_BUCKET}/wicked-woods-ome/ --delete --exclude "${{ github.event.repository.name }}.zip"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"