name: Run CI tool to validate schedule

on:
  push:
    branches:
      - main
      - linter

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO: ometools/open-music-event
      BINARY_NAME: open-music-event

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: get_release
        run: |
          TAG=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" | jq -r .tag_name)
          echo "Latest release tag is $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # - name: Download CLI binary from latest release
      #   run: |
      #     TAG=${{ steps.get_release.outputs.tag }}
      #     DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${TAG}/${BINARY_NAME}"

      #     echo "Downloading $BINARY_NAME from $DOWNLOAD_URL"
      #     curl -sL "$DOWNLOAD_URL" -o "$BINARY_NAME"
      #     chmod +x "$BINARY_NAME"

      - name: Download CLI binary
        run: |
          DOWNLOAD_URL="https://github.com/ometools/open-music-event/actions/runs/15747122889/artifacts/3359595376"
          curl -sL "$DOWNLOAD_URL" -o $BINARY_NAME.zip
          pwd
          ls

      - name: Unzip
        run: |
          unzip ${BINARY_NAME}.zip
          ls
          chmod +x ${BINARY_NAME}


      - name: Run CLI tool
        run: |
          ./${BINARY_NAME} validate ./2024/wicked-woods-ome